/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // shadcn compatibility
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // MD3 Wireframe Design System - Light
        "surface-variant": "#e2e2e2",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-low": "#f3f3f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "outline-variant": "#cfc4c5",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1b1b1b",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-container": "#848484",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary-fixed-variant": "#474747",
        "on-tertiary-container": "#848484",
        "tertiary-fixed": "#e2e2e2",
        "inverse-primary": "#c6c6c6",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#474747",
        "inverse-on-surface": "#f1f1f1",
        "secondary-fixed-dim": "#c7c6c6",
        "secondary-fixed": "#e4e2e2",
        "on-secondary-fixed-variant": "#464747",
        "tertiary-fixed-dim": "#c6c6c6",
        "primary-fixed-dim": "#c6c6c6",
        "outline": "#7e7576",
        "on-secondary-container": "#626262",
        "inverse-surface": "#2f3131",
        "surface-tint": "#5e5e5e",
        "primary-container": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "tertiary-container": "#1b1b1b",
        "secondary-container": "#e1dfdf",
        "primary-fixed": "#e2e2e2",
        "on-error": "#ffffff",
        "tertiary": "#000000",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "on-background": "#1a1c1c",
        "background": "#f9f9f9",
        "error": "#ba1a1a",
      },
      fontFamily: {
        display: ["Geist", "Hanken Grotesk", "sans-serif"],
        "display-lg": ["Geist", "Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Geist", "Hanken Grotesk", "sans-serif"],
        "headline-md": ["Geist", "Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Geist", "Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "gutter": "24px",
        "lg": "24px",
        "xl": "48px",
        "sidebar-width": "280px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        typing: {
          "0%": { width: "0" },
          "100%": { width: "100%" },
        },
        "blink-caret": {
          "0%, 100%": { borderColor: "transparent" },
          "50%": { borderColor: "black" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "scale(0.98) translateY(4px)" },
          to: { opacity: "1", transform: "scale(1) translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        typing: "typing 3.5s steps(40, end)",
        "blink-caret": "blink-caret 0.75s step-end infinite",
        "fade-in": "fade-in 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};
